config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get  "auth/:provider", to: "sessions#create", as: 'login'
  get "/auth/:provider/callback", to: "sessions#create"

  resources :users, only: [:show, :edit, :update]
  resources :pets, only: [:new, :create]
  resources :inventories, only: [:new, :create, :edit, :update]

  get "users/:id/remove_pet", to: "users#remove_pet", as: 'remove_pet'
  post "regenerate", to: "pets#regenerate_token", as: "regenerate"
  get "/schedules", to: "schedule#index", as: "schedules"

  get "logout", to: "sessions#destroy", as: "logout"

  post "/feed_request", to: "pi#feed_request", as: "feed_request"
  get "/new_schedule", to: "pi#new_schedule", as: "schedule"
  patch "/set_timer", to: "pi#set_timer", as: "timer"
  put "/cancel_feeding", to: "pi#cancel_feeding", as: "cancel"

  get "/api/v1/requests/new", to: "api/v1/requests#run_pi", as: "pi"
  put "/api/v1/requests/confirmation", to: "api/v1/requests#confirmation", as: "pi_confirmation"

  get "/check_db", to: "home#check_db", as: "check_db"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Validations
  validates :name, presence: true

  # Associations
  belongs_to :pets

  def self.find_or_create_user(auth_hash)
    uid = auth_hash.uid

    if User.find_by(uid: uid)
      user = User.find_by(uid: uid)
    elsif user = User.create(
      uid: uid,
      nickname: auth_hash.info.nickname,
      name: auth_hash.info.name,
      profile_image: auth_hash.info.image,
      token: auth_hash.credentials.token,
      secret: auth_hash.credentials.secret
      )

      user.save
    end

    return user
  end

  def twitter
    @client ||= Twitter::REST::Client.new do |config|
      config.consumer_key        = ENV["TWITTER_CLIENT_ID"]
      config.consumer_secret     = ENV["TWITTER_CLIENT_SECRET"]
      config.access_token        = token
      config.access_token_secret = secret
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login

  def show
    @user = User.find(session[:user_id])
    if @user.pet_id != nil
      @pet = Pet.find(@user.pet_id)
      scheduled_feedings = Schedule.all
      @scheduled_feedings = scheduled_feedings.order(:time)
      @inventory = Inventory.find_by(pet_id: @pet.id)
    end
  end

  def edit
    @user = User.find(session[:user_id])
  end

  def update
    user = User.find(session[:user_id])
    token = params[:user][:pet_id]
    token.strip!

    pet = Pet.find_by(api_key: token)

    if pet != nil
      user.pet_id = pet.id
      user.save
      redirect_to root_path
    else
      flash[:notice] = "This pet could not be found"
      redirect_to root_path
    end
  end

  def remove_pet
    user = User.find(session[:user_id])
    @pet = Pet.find(user.pet_id)
    user.pet_id = nil
    user.save
    flash[:notice] = "You have successfully unlinked from the feeder."
    redirect_to root_path
  end

  private

  # Final feature -- feedings past week
  # def find_daily_average(pet)
  #   feedings = Feeding.where("pet_id = ?", pet.id)

  #   total_feedings = feedings.all.length


  # end

  def create_params
    params.permit(user: [:pet_id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="page-header">
    <%= link_to root_path, class: "btn btn-default" do %><i class="glyphicon glyphicon-home"></i>
    <% end %>
</div>

<div class="new_pet_form">
  <h2>Please search for your pet below.</h2>

  <%= form_for @user do |f| %>
    <%= f.label "Add pet token here" %>
    <%= f.text_field :pet_id %>

    <%= f.submit "Search for Pet" %>
  <% end %>
</div>

app/views/users/show.html.erb
 <div class="page-header">
    <%= link_to root_path, { :'data-no-turbolink' =>  "true" }  do %><button class="btn btn-default"><i class="glyphicon glyphicon-home"></i></button>
    <% end %>
    <h5 id="logged_in">Logged in as: <%= @user.name %></h5>
    <%= image_tag(@user.profile_image, size: "40x37", class: "profile_image") %>
</div>

<br>
<br>

<% if @user.pet_id != nil %>

  <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
    <div class="panel panel-default">
      <div class="panel-heading" role="tab" id="headingOne">
        <h4 class="panel-title">
          <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
            Pet Token
          </a>
        </h4>
      </div>
      <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
        <div class="panel-body">
      <% if @pet.master_user == @user.id %>
          <h6>This token should only be shared with people you trust to feed your pet. It will allow them access to your feeder.</h6>
          <%= @pet.api_key %>
          <br>
          <%= button_to "Regenerate Pet Token", regenerate_path, class: "btn btn-default" %>
          <br>
      <% end %>
          <%= button_to "Unlink to #{@pet.name}'s feeder", remove_pet_path(session[:user_id]), method: :get, class: "btn btn-default" %>
        </div>
      </div>
    </div>

    <div class="panel panel-default">
      <div class="panel-heading" role="tab" id="headingTwo">
        <h4 class="panel-title">
          <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
            Food Supply
          </a>
        </h4>
      </div>
      <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
        <div class="panel-body">
        <% if @inventory == nil %>
          Track food inventory
          <br>
          <%= link_to "Add feeder information", new_inventory_path, class: "btn btn-default" %>
        <% end %>
        <% if @inventory != nil %>
          Current Food Supply <%= @inventory.current_supply %> ounces
          <br>
          <br>
          Update Current Supply
          <br>
          <%= link_to "Update", edit_inventory_path, class: "btn btn-default" %>
        <% end %>
        </div>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading" role="tab" id="headingThree">
        <h4 class="panel-title">
          <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
            <!-- Average Daily Food Intake -->
            Robot Feeder Tutorial
          </a>
        </h4>
      </div>
      <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
        <div class="panel-body">
          <!-- Some more stat info that I haven't sorted out yet. -->
          Available on <a href="https://github.com/lilagrc/Capstone----RoboPig/blob/master/Instructions.md">Github</a>
        </div>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading" role="tab" id="headingFour">
        <h4 class="panel-title">
          <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
            Current Feed Schedule
          </a>
        </h4>
      </div>
      <div id="collapseFour" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFour">
        <div class="panel-body">
          <%= render 'schedule/schedule_index' %>
        </div>
      </div>
    </div>
  </div>

<% else %>
    <h2>You have no registered pets.</h2>
<% end %>