config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get  "auth/:provider", to: "sessions#create", as: 'login'
  get "/auth/:provider/callback", to: "sessions#create"

  resources :users, only: [:show, :edit, :update]
  resources :pets, only: [:new, :create]
  resources :inventories, only: [:new, :create, :edit, :update]

  get "users/:id/remove_pet", to: "users#remove_pet", as: 'remove_pet'
  post "regenerate", to: "pets#regenerate_token", as: "regenerate"
  get "/schedules", to: "schedule#index", as: "schedules"

  get "logout", to: "sessions#destroy", as: "logout"

  post "/feed_request", to: "pi#feed_request", as: "feed_request"
  get "/new_schedule", to: "pi#new_schedule", as: "schedule"
  patch "/set_timer", to: "pi#set_timer", as: "timer"
  put "/cancel_feeding", to: "pi#cancel_feeding", as: "cancel"

  get "/api/v1/requests/new", to: "api/v1/requests#run_pi", as: "pi"
  put "/api/v1/requests/confirmation", to: "api/v1/requests#confirmation", as: "pi_confirmation"

  get "/check_db", to: "home#check_db", as: "check_db"

end

app/models/feeding.rb
class Feeding < ActiveRecord::Base
  # Associations
  belongs_to :pet
end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
  # Validations
  validates :pet_id, uniqueness: true

  # Associations
  belongs_to :pet
end

app/models/pet.rb
class Pet < ActiveRecord::Base
  #Validations
  validates :name, presence: true

  #Associations
  has_many :users
  has_many :feedings
  has_many :requests
  has_many :inventories

  def self.generate_api_key
      token = SecureRandom.base64.tr('+/=', 'Qrt')
  end

end

app/models/request.rb
class Request < ActiveRecord::Base
  # Associations
  belongs_to :pet

  # Validations
  validates :pet_id, presence: true
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Validations
  validates :name, presence: true

  # Associations
  belongs_to :pets

  def self.find_or_create_user(auth_hash)
    uid = auth_hash.uid

    if User.find_by(uid: uid)
      user = User.find_by(uid: uid)
    elsif user = User.create(
      uid: uid,
      nickname: auth_hash.info.nickname,
      name: auth_hash.info.name,
      profile_image: auth_hash.info.image,
      token: auth_hash.credentials.token,
      secret: auth_hash.credentials.secret
      )

      user.save
    end

    return user
  end

  def twitter
    @client ||= Twitter::REST::Client.new do |config|
      config.consumer_key        = ENV["TWITTER_CLIENT_ID"]
      config.consumer_secret     = ENV["TWITTER_CLIENT_SECRET"]
      config.access_token        = token
      config.access_token_secret = secret
    end
  end

end

app/controllers/feedings_controller.rb
class FeedingsController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if session[:user_id]
      @user = User.find(session[:user_id])
      if @user.pet_id != nil
        @pet = Pet.find(@user.pet_id)
        find_num_feedings
      end
    end
  end

  # Checks for updated feedings in DB and works with AJAX to trigger confirmation alert
  def check_db
    feedings = find_num_feedings

    render json: {num: feedings}
  end

  private

  def find_num_feedings
  user = User.find(session[:user_id])
  pet = Pet.find(user.pet_id)
  feedings = Feeding.where("created_at >= ? AND pet_id = ?", Time.zone.now.beginning_of_day, pet.id)

  @num_feedings = feedings.size

  return @num_feedings
  end

end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :require_login

  def new
    @pet = Pet.new
  end

  def create
    user = User.find(session[:user_id])
    pet = Pet.create(create_params[:pet])
    pet.api_key = Pet.generate_api_key
    pet.master_user = user.id
    user.pet_id = pet.id
    user.save

    if pet.save
        flash[:notice] = "Congratulations! You have now registered with Robo Pets. Please see your profile page for an API token which can be used for your robo device."
        redirect_to root_path
    else
      render 'new'
    end
  end

  def regenerate_token
    @pet.api_key = Pet.generate_api_key
    @pet.save

    remove_pet_links(@pet)

    redirect_to user_path(session[:user_id])
  end

  private

  def create_params
    params.permit(pet: [:name, :breed])
  end

  def remove_pet_links(pet)
    users = pet.users

    users.each do |user|
      unless pet.master_user == user.id
        user.pet_id = nil
        user.save
      end
    end
  end
end

app/controllers/pi_controller.rb
class PiController < ApplicationController
  before_action :require_login
  before_action :find_pet

  # Updates API response to include feed request
  def feed_request
    request = Request.where(pet_id: @pet.id).first_or_initialize
    request.schedule = nil
    request.body = "feed"
    request.save

    redirect_to root_path
  end

  def new_schedule
    @request = Request.where(pet_id: @pet.id).first_or_initialize
    @request.schedule = nil
    @request.body = nil
    @request.save

    respond_to do |format|
      format.html { render :layout => false, :partial => 'home/schedule'}
    end
  end

  # Updates API response to send schedule request
  def set_timer
    request = Request.find_by(pet_id: @pet.id)
    request.schedule = params["request"]["schedule"]
    request.save
    flash[:notice] = "Your feeding has been scheduled. You can schedule another feeding time by clicking 'Schedule a Feeding'"

    add_new_schedule

    redirect_to root_path
  end

  # Updates API response to send cancel scheduled feedings request
  def cancel_feeding
    request = Request.find_by(pet_id: @pet.id)
    request.body = nil
    request.schedule = "cancel"
    request.save
    flash[:notice] = "Your feedings have been cancelled"

    remove_scheduled_feedings

    redirect_to root_path
  end

  private

  def add_new_schedule
    s = Schedule.create(time: params["request"]["schedule"])
    s.save
  end

  def remove_scheduled_feedings
    Schedule.delete_all
  end

end

app/controllers/schedule_controller.rb
class ScheduleController < ApplicationController

  #TO DO -- tie schedule to pet
  def index
    scheduled_feedings = Schedule.all
    @scheduled_feedings = scheduled_feedings.order(:time)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login

  def show
    @user = User.find(session[:user_id])
    if @user.pet_id != nil
      @pet = Pet.find(@user.pet_id)
      scheduled_feedings = Schedule.all
      @scheduled_feedings = scheduled_feedings.order(:time)
      @inventory = Inventory.find_by(pet_id: @pet.id)
    end
  end

  def edit
    @user = User.find(session[:user_id])
  end

  def update
    user = User.find(session[:user_id])
    token = params[:user][:pet_id]
    token.strip!

    pet = Pet.find_by(api_key: token)

    if pet != nil
      user.pet_id = pet.id
      user.save
      redirect_to root_path
    else
      flash[:notice] = "This pet could not be found"
      redirect_to root_path
    end
  end

  def remove_pet
    user = User.find(session[:user_id])
    @pet = Pet.find(user.pet_id)
    user.pet_id = nil
    user.save
    flash[:notice] = "You have successfully unlinked from the feeder."
    redirect_to root_path
  end

  private

  # Final feature -- feedings past week
  # def find_daily_average(pet)
  #   feedings = Feeding.where("pet_id = ?", pet.id)

  #   total_feedings = feedings.all.length


  # end

  def create_params
    params.permit(user: [:pet_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def logged_in?
    unless session[:user_id] == nil
      return true
    end
  end
end

app/helpers/feedings_helper.rb
module FeedingsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/pi_helper.rb
module PiHelper
end

app/helpers/schedule_helper.rb
module ScheduleHelper

  def format_time(time)
    time = time.to_i

    if time == 0
      time = "12am"
    elsif time > 12
      time = "#{time - 12}" + "pm"
    else
      time = "#{time}" + "am"
    end

    return time
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/_schedule.html.erb
<p class="schedule_form_header">
  <ul>
    <li>Hours are in military time (0-23, 13 = 1pm).</li>
    <li>This will feed your pet at the same time each day.</li>
    <li>You can only enter one feeding at a time.</li>
  </ul>
</p>

<div class="row">
  <div class="col-md-6">
    <%= form_for @request, url: timer_path do |f| %>
      <div class="form-group">
        <fieldset>
          <%= f.label "Feed Time", class: "schedule_label" %>
          <%= f.select :schedule, options_for_select(0..23) %>

          <%= f.submit "Submit", class: "btn btn-default" %>
        </fieldset>
      </div>
    <% end %>
    <p><%= link_to "View current feeding schedule", schedules_path  %></p>
  </div>
</div>

app/views/home/index.html.erb
<% if logged_in? %>

<script>window.twttr = (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0],
      t = window.twttr || {};
    if (d.getElementById(id)) return t;
    js = d.createElement(s);
    js.id = id;
    js.src = "https://platform.twitter.com/widgets.js";
    fjs.parentNode.insertBefore(js, fjs);
    t._e = [];
    t.ready = function(f) {
      t._e.push(f);
    };
    return t;
  }(document, "script", "twitter-wjs"));
</script>

<div class="page-header">
  <div class="dropdown">
    <button type="button" class="btn dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true" aria-label="Left Align">
      <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
    </button>
    <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
      <% if logged_in? %>
        <li><%= link_to "Profile", user_path(session[:user_id]) %></li>
        <li><%= link_to "Log Out", logout_path %></li>
      <% end %>
    </ul>
  </div>
    <% today = Time.now.strftime("%I:%M,%m/%d") %>
    <% url = "https://twitter.com/intent/tweet?text=Fed%20my%20fat%20cat%20at%20" + today.to_s + "%20via" %>
    <a class="twitter-share-button" href=<%= url %> data-size="large" data-count value="none"> Tweet</a>
</div>
<% end %>

<div class="row" id="header_text">
  <h1>Robo Feeder</h1>
</div>

<div class="twitter_login">
  <% unless logged_in? %>
    <%= link_to image_tag('sign-in-with-twitter-gray.png'), login_path('twitter')%>
  <% end %>
</div>

<% if logged_in? %>
<br>
  <% if @user.pet_id != nil %>
    <div class="row">
      <div class="col-xs-12", id="feed_details">
        <h3><%= @pet.name %> has been fed <div class="num_feedings"><%= @num_feedings %></div> times today</h3>
      </div>
    </div>
    <br>
    <br>
    <div class="row">
      <div class="col-xs-12">
        <%= button_to "Feed Now", feed_request_path, class: "btn btn-default", id: "feed_button" %>
        <br>
        <%= button_to "Schedule a Feeding", schedule_path, method: :get, class: "btn btn-default", id: "schedule_button" %>
        <div class="schedule_form">

        </div>
        <br>
      <% unless Schedule.all == [] %>
        <%= button_to "Cancel Feedings", cancel_path, method: :put, data: { confirm: "This will delete all schedule feedings. Proceed?"}, class: "btn btn-default", id: "cancel_button" %>
      <% end %>
      </div>
    </div>

  <% else %>
    <div class="row">
      <div class="col-xs-12", id="landing_page">
        <h3><%= link_to "Register your robo feeder!",  new_pet_path(session[:user_id]) %></h3>
        <h3><%= link_to "Find Feeder", edit_user_path(session[:user_id]) %></h3>
        <h5>If you have been given access to a registered feeder, you can link to their account below. You will need the correct pet token.</h5>
        <h3>Tutorial for Building Feeder </h3>
      </div>
  <% end %>
<% else %>
  <br>
  <br>
  <br>
    <div class="row">
      <div class="col-xs-12", id="landing_page">
        <h4>Robo Feed is a site for people wishing to build their own robot pet feeders. This site allows you to link up to your feeder and feed your pet remotely. Full tutorial instructions for building your own robot pet feeder are available <a href="https://github.com/lilagrc/Capstone----RoboPig/blob/master/Instructions.md">here</a> on Github</h4>
      </div>
    </div>
<% end %>